### PR TITLE
Add support for downloading artifacts from an authenticated Maven repo.

### PR DESCRIPTION
**Pull request by udat**

### CODE REVIEW

**Comment by mapoulin** [comment]
Any plan on merging this? It seems that 4 years later, your plugin is still a reference for connecting to authenticated maven repositories.

**Comment by sebersole** [comment]
Really?  Sweet.

TBH I only really did this plugin as I needed it for Hibernate, but I'll
look over this next week.

**Comment by sebersole** [comment]
FWIW, if you are not willing I will get to the change eventually

**Comment by mapoulin** [comment]
We have found a workaround solution using gradle property files and unencrypted password. Your solution would be better but this is not a priority for me right now. I'll try to free up some time this weekend but I can't guarantee anything.

**Pull request merged**
